# Namespace for development stage - all successful builds will be pushed to dev
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# Namespace for staging stage - all performance tested builds will be pushed to staging
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
# Namespace for production stage - at a specific point in time, the artefacts in staging will be
# marked for production and then deployed to the production namespace
apiVersion: v1
kind: Namespace
metadata:
  name: production